name: img_seg_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - scipy
  - opencv
  - jupyter
  - notebook
  - ipykernel
  - pytorch
  - torchvision
  - cudatoolkit=11.8
  - pip:
    - tensorflow
    - segmentation-models-pytorch
    - albumentations
    - tensorboard
    - wandb
    - tqdm
    - pyyaml
    - python-dotenv